// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RoundingPortal_API.Data;

#nullable disable

namespace RoundingPortal_API.Migrations
{
    [DbContext(typeof(RoundingContext))]
    [Migration("20250424070013_Add SLA")]
    partial class AddSLA
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RoundingPortal_API.Models.Issue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LabId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReportedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ReporterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SLA")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("WorkstationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LabId");

                    b.HasIndex("ReporterId");

                    b.HasIndex("WorkstationId");

                    b.ToTable("Issues");
                });

            modelBuilder.Entity("RoundingPortal_API.Models.Lab", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastRoundedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("MaxSeats")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PreviousRounderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PreviousRounderId");

                    b.ToTable("Labs");
                });

            modelBuilder.Entity("RoundingPortal_API.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RoundingPortal_API.Models.Workstation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LabId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LabId");

                    b.ToTable("Workstations");
                });

            modelBuilder.Entity("RoundingPortal_API.Models.WorkstationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Boot_To_Windows")
                        .HasColumnType("int");

                    b.Property<int>("Browser")
                        .HasColumnType("int");

                    b.Property<int>("Conduiting")
                        .HasColumnType("int");

                    b.Property<int>("DeepFreeze_Frozen")
                        .HasColumnType("int");

                    b.Property<string>("DeepFreeze_Policy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Display")
                        .HasColumnType("int");

                    b.Property<int>("Domain")
                        .HasColumnType("int");

                    b.Property<int>("Kensington_Lock")
                        .HasColumnType("int");

                    b.Property<int>("Microsoft_Office")
                        .HasColumnType("int");

                    b.Property<int>("Microsoft_Teams")
                        .HasColumnType("int");

                    b.Property<int>("Mouse_Keyboard")
                        .HasColumnType("int");

                    b.Property<Guid>("RounderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Shift")
                        .HasColumnType("int");

                    b.Property<int>("Tidiness")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WorkstationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RounderId");

                    b.HasIndex("WorkstationId");

                    b.ToTable("WorkstationRecords");
                });

            modelBuilder.Entity("RoundingPortal_API.Models.Issue", b =>
                {
                    b.HasOne("RoundingPortal_API.Models.Lab", "Lab")
                        .WithMany()
                        .HasForeignKey("LabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RoundingPortal_API.Models.User", "Reporter")
                        .WithMany()
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RoundingPortal_API.Models.Workstation", "Workstation")
                        .WithMany()
                        .HasForeignKey("WorkstationId");

                    b.Navigation("Lab");

                    b.Navigation("Reporter");

                    b.Navigation("Workstation");
                });

            modelBuilder.Entity("RoundingPortal_API.Models.Lab", b =>
                {
                    b.HasOne("RoundingPortal_API.Models.User", "PreviousRounder")
                        .WithMany()
                        .HasForeignKey("PreviousRounderId");

                    b.Navigation("PreviousRounder");
                });

            modelBuilder.Entity("RoundingPortal_API.Models.Workstation", b =>
                {
                    b.HasOne("RoundingPortal_API.Models.Lab", "Lab")
                        .WithMany()
                        .HasForeignKey("LabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lab");
                });

            modelBuilder.Entity("RoundingPortal_API.Models.WorkstationRecord", b =>
                {
                    b.HasOne("RoundingPortal_API.Models.User", "Rounder")
                        .WithMany()
                        .HasForeignKey("RounderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RoundingPortal_API.Models.Workstation", "Workstation")
                        .WithMany()
                        .HasForeignKey("WorkstationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rounder");

                    b.Navigation("Workstation");
                });
#pragma warning restore 612, 618
        }
    }
}
